### ISSUE TITLE
Error When Try To Using Setup

### ISSUE THREAD

**Issue by bimaindrawans** [NICK-FURY-6023/Temporary-voice-channel-discord-bot#2]
when try to using setup, nothing happend ( just my message got deleted) but the embed didn't showed up.

**Comment by bimaindrawans** [comment]
![Screenshot 2023-12-21 230618](https://github.com/NICK-FURY-6023/Temporary-voice-channel-discord-bot/assets/147312348/54579fc2-813b-4f77-9624-5c1e9164d5e0)
the join to create function is working properly, but when i try to using setup, nothing show up and there's no error log in terminal

**Comment by bimaindrawans** [comment]
my bad, forget to remove // on rowOne

**Comment by NICK-FURY-6023** [comment]
> my bad, forget to remove // on rowOne

Now it's working or not iff you have isuue contact with me on Discord server link in my readme

**Comment by bimaindrawans** [comment]
it's working perfectly, but i think i need to add more features on this code, like change region, transfer ownership and claim ownership, i already try to doing that using chatgpt but it's not work, can i ask you help to review my code ?

**Comment by bimaindrawans** [comment]
thankyou for this great code

**Comment by NICK-FURY-6023** [comment]
> it's working perfectly, but i think i need to add more features on this code, like change region, transfer ownership and claim ownership, i already try to doing that using chatgpt but it's not work, can i ask you help to review my code ?

**Okay contact with me tomorrow in discord 11 am**
